import { useState } from "react";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
    DialogFooter,
    DialogTrigger
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import {
    FileText,
    Download,
    FileJson,
    Settings,
    Clock,
    ShieldCheck,
    Loader2
} from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";

interface ReportModalProps {
    triggerLabel?: string;
    title?: string;
}

export function ReportModal({
    triggerLabel = "Generate Report",
    title = "Tactical Intel Report"
}: ReportModalProps) {
    const [isGenerating, setIsGenerating] = useState(false);
    const [progress, setProgress] = useState(0);
    const [open, setOpen] = useState(false);

    const generateReport = () => {
        setIsGenerating(true);
        setProgress(0);

        // Simulate generation process
        const interval = setInterval(() => {
            setProgress((prev) => {
                if (prev >= 100) {
                    clearInterval(interval);

                    // Trigger actual file download
                    const reportData = {
                        title: title,
                        generatedAt: new Date().toISOString(),
                        status: "Verified",
                        threats: [
                            { id: 1, title: "AWS IAM Escalation", severity: "Critical" },
                            { id: 2, title: "SaaS API Logic Flaw", severity: "High" }
                        ],
                        summary: "This is a simulated security intelligence report generated by H3M4 VAULT."
                    };

                    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
                    const url = window.URL.createObjectURL(blob);
                    const link = document.createElement('a');
                    link.href = url;
                    link.download = `${title.toLowerCase().replace(/\s+/g, '_')}_${new Date().getTime()}.json`;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                    window.URL.revokeObjectURL(url);

                    setTimeout(() => {
                        setIsGenerating(false);
                        setOpen(false);
                        toast.success(`${title} Generated Successfully`, {
                            description: "The report has been compiled and saved to your downloads.",
                        });
                    }, 500);
                    return 100;
                }
                return prev + 5;
            });
        }, 100);
    };

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
                <Button className="bg-primary text-primary-foreground hover:bg-primary/90 flex items-center gap-2">
                    {triggerLabel === "Export Audit Report" && <Download className="h-4 w-4" />}
                    {triggerLabel}
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-md bg-card/95 backdrop-blur-xl border-border">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <FileText className="h-5 w-5 text-primary" />
                        {title}
                    </DialogTitle>
                    <DialogDescription>
                        Generate a comprehensive security overview of verified threats and system status.
                    </DialogDescription>
                </DialogHeader>

                {!isGenerating ? (
                    <div className="space-y-6 py-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div className="flex flex-col gap-2 p-3 rounded-lg border border-border bg-background/50 hover:border-primary/50 transition-colors cursor-pointer group">
                                <div className="bg-primary/10 w-fit p-2 rounded-md group-hover:bg-primary/20 transition-colors">
                                    <ShieldCheck className="h-4 w-4 text-primary" />
                                </div>
                                <div>
                                    <div className="text-sm font-semibold">Executive</div>
                                    <div className="text-xs text-muted-foreground">High-level summary for C-suite</div>
                                </div>
                            </div>
                            <div className="flex flex-col gap-2 p-3 rounded-lg border border-primary/50 bg-primary/5 hover:border-primary/80 transition-colors cursor-pointer group shadow-[0_0_15px_-5px_rgba(var(--primary),0.1)]">
                                <div className="bg-primary/20 w-fit p-2 rounded-md">
                                    <Settings className="h-4 w-4 text-primary" />
                                </div>
                                <div>
                                    <div className="text-sm font-semibold">Technical</div>
                                    <div className="text-xs text-muted-foreground">Deep dive into CVEs & IOCs</div>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-3">
                            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Report Parameters</label>
                            <div className="space-y-2">
                                <div className="flex items-center justify-between p-2 rounded border border-border bg-background/30 text-sm">
                                    <div className="flex items-center gap-2">
                                        <Clock className="h-4 w-4 text-muted-foreground" />
                                        <span>Last 24 Hours</span>
                                    </div>
                                    <Button variant="ghost" size="sm" className="h-7 text-xs">Change</Button>
                                </div>
                                <div className="flex items-center justify-between p-2 rounded border border-border bg-background/30 text-sm">
                                    <div className="flex items-center gap-2">
                                        <FileJson className="h-4 w-4 text-muted-foreground" />
                                        <span>JSON + PDF Format</span>
                                    </div>
                                    <Button variant="ghost" size="sm" className="h-7 text-xs">Change</Button>
                                </div>
                            </div>
                        </div>
                    </div>
                ) : (
                    <div className="space-y-6 py-10 text-center">
                        <div className="flex justify-center">
                            <div className="relative">
                                <Loader2 className="h-12 w-12 text-primary animate-spin opacity-20" />
                                <div className="absolute inset-0 flex items-center justify-center">
                                    <span className="text-xs font-mono font-bold">{progress}%</span>
                                </div>
                            </div>
                        </div>
                        <div className="space-y-2">
                            <div className="text-sm font-medium">Analyzing verified threat vectors...</div>
                            <Progress value={progress} className="h-1.5" />
                            <p className="text-xs text-muted-foreground animate-pulse">Compiling real-time data from 452 active researchers</p>
                        </div>
                    </div>
                )}

                <DialogFooter>
                    {!isGenerating && (
                        <Button
                            onClick={generateReport}
                            className="w-full flex items-center gap-2"
                        >
                            <Download className="h-4 w-4" />
                            Compile & Export Report
                        </Button>
                    )}
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
